image: gitpod/workspace-postgres

ports:
  - name: frontend
    port: 3000
    onOpen: open-preview
  
  - name: backend
    port: 3001
    onOpen: ignore
    visibility: public

  - name: database
    port: 5432
    onOpen: ignore

tasks:
  - init: |
      npm install
      chmod +x ./init-db.sh
      ./init-db.sh
    command: |
      npm run start